apiVersion: hypershift.openshift.io/v1beta1
kind: HostedCluster
metadata:
  name: base-cluster
  namespace: clusters
  labels:
    "cluster.open-cluster-management.io/clusterset": default
spec:
  channel: stable-4.18
  managementType: Managed
  release:
    image: quay.io/openshift-release-dev/ocp-release:4.18.23-multi
  pullSecret:
    name: pullsecret-cluster-base-cluster
  sshKey:
    name: sshkey-cluster-base-cluster
  etcd:
    managed:
      storage:
        type: PersistentVolume
        persistentVolume:
          size: 8Gi
          storageClassName: ocs-external-storagecluster-ceph-rbd 
  networking:
    networkType: OVNKubernetes
    clusterNetwork:
      - cidr: 10.128.0.0/14
    serviceNetwork:
      - cidr: 172.30.0.0/16
  platform:
    type: KubeVirt
    kubevirt:
      baseDomainPassthrough: true
  infraID: base-cluster
  controllerAvailabilityPolicy: HighlyAvailable
  infrastructureAvailabilityPolicy: HighlyAvailable
  services:
    - service: OAuthServer
      servicePublishingStrategy:
        type: Route
    - service: OIDC
      servicePublishingStrategy:
        type: Route
    - service: Konnectivity
      servicePublishingStrategy:
        type: Route
    - service: Ignition
      servicePublishingStrategy:
        type: Route
