apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hcp-fleet-manager
  namespace: openshift-gitops
spec:
  generators:
    - git:
        repoURL: 'https://github.com/SerenaFlocco/ocp-gitops-fleet.git'
        revision: HEAD
        files:
          - path: "clusters/*.yaml"
  template:
    metadata:
      name: '{{clusterName}}'
    spec:
      project: hcp-fleet-project
      source:
        repoURL: 'https://github.com/SerenaFlocco/ocp-gitops-fleet.git'
        targetRevision: HEAD
        path: helm
        helm: 
          valueFiles:
            - ../clusters/{{clusterName}}.yaml 
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: clusters
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
