apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: hcp-fleet-project
  namespace: openshift-gitops
spec:
  description: "Enterprise Project for Hosted Control Planes Fleet Management"
  sourceRepos:
    - 'https://github.com/SerenaFlocco/ocp-gitops-fleet.git'
  destinations:
    - namespace: '*'
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: 'cluster.open-cluster-management.io'
      kind: 'ManagedCluster'
