apiVersion: hypershift.openshift.io/v1beta1
kind: NodePool
metadata:
  name: base-cluster-worker-pool
spec:
  platform:
    kubevirt:
      additionalNetworks:
      - name: openshift-cnv/<network_name> # the network defined via NMState: in this case all network definitions are in the “openshift-cnv” namespace

