apiVersion: hypershift.openshift.io/v1beta1
kind: HostedCluster
metadata:
  name: base-cluster
spec:
  configuration:
    proxy:
      httpProxy: http://myproxy.enterprise.lan:8080
      httpsProxy: http://myproxy.enterprise.lan:8080
      noProxy: <CIDRs_and_domains> # specify all the domains and network CIDRs for both the management and the hosted clusters
